# Generated by Django 5.1.7 on 2025-03-22 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationcommittee",
            name="is_founder",
            field=models.BooleanField(
                default=False, help_text="Is Founder", verbose_name="is founder"
            ),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="User Designation",
                        max_length=255,
                        verbose_name="designation",
                    ),
                ),
                (
                    "preferred_categories",
                    models.CharField(
                        choices=[
                            ("music", "Music"),
                            ("nightlife", "Nightlife"),
                            ("concert", "Concert"),
                            ("holidays", "Holidays"),
                            ("dating", "Dating"),
                            ("hobbies", "Hobbies"),
                            ("business", "Business"),
                            ("food_drink", "Food & Drink"),
                        ],
                        help_text="Category",
                        max_length=50,
                        verbose_name="preferred_category",
                    ),
                ),
                (
                    "allow_marketing_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Allow Marketing Emails",
                        verbose_name="marketing emails",
                    ),
                ),
                (
                    "allow_event_updates",
                    models.BooleanField(
                        default=True,
                        help_text="Allow Event Updates",
                        verbose_name="event updates",
                    ),
                ),
                (
                    "allow_system_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Allow System Notifications",
                        verbose_name="system notifications",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated At", verbose_name="updated at"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
            },
        ),
    ]
