# Generated by Django 5.1.7 on 2025-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name", max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "scan_id",
                    models.CharField(
                        help_text="Scan ID", max_length=10, verbose_name="scan id"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description", verbose_name="description"
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="Start Datetime", verbose_name="start datetime"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        help_text="End Datetime", verbose_name="end datetime"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("music", "Music"),
                            ("nightlife", "Nightlife"),
                            ("concert", "Concert"),
                            ("holidays", "Holidays"),
                            ("dating", "Dating"),
                            ("hobbies", "Hobbies"),
                            ("business", "Business"),
                            ("food_drink", "Food & Drink"),
                        ],
                        help_text="Category",
                        max_length=50,
                        verbose_name="category",
                    ),
                ),
                ("tags", models.JSONField(help_text="Tags", verbose_name="tags")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="Type",
                        max_length=255,
                        verbose_name="type",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location", max_length=255, verbose_name="location"
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=9)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        help_text="Status",
                        max_length=255,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated At", verbose_name="updated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="EventAttendees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_present",
                    models.BooleanField(
                        default=False, help_text="Is Present", verbose_name="is present"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated At", verbose_name="updated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Attendee",
                "verbose_name_plural": "Event Attendees",
            },
        ),
        migrations.CreateModel(
            name="EventFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(help_text="Rating", verbose_name="rating"),
                ),
                (
                    "feedback",
                    models.TextField(help_text="Feedback", verbose_name="feedback"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated At", verbose_name="updated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Feedback",
                "verbose_name_plural": "Event Feedbacks",
            },
        ),
        migrations.CreateModel(
            name="EventInteractions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("view", "View"),
                        ],
                        help_text="Interaction Type",
                        max_length=255,
                        verbose_name="interaction type",
                    ),
                ),
                (
                    "interaction_data",
                    models.JSONField(
                        help_text="Interaction Data", verbose_name="interaction data"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Interaction",
                "verbose_name_plural": "Event Interactions",
            },
        ),
        migrations.CreateModel(
            name="EventNotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_config",
                    models.JSONField(
                        help_text="Notification Config",
                        verbose_name="notification config",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated At", verbose_name="updated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Notification Config",
                "verbose_name_plural": "Event Notification Configs",
            },
        ),
    ]
