# Generated by Django 5.1.7 on 2025-03-21 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                help_text="Created By",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organisation",
            field=models.ForeignKey(
                help_text="Organisation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="users.organisation",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="eventattendees",
            name="attendee",
            field=models.ForeignKey(
                help_text="Attendee",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_attended",
                to=settings.AUTH_USER_MODEL,
                verbose_name="attendee",
            ),
        ),
        migrations.AddField(
            model_name="eventattendees",
            name="event",
            field=models.ForeignKey(
                help_text="Event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_attendees",
                to="events.event",
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                through="events.EventAttendees", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="eventfeedback",
            name="event",
            field=models.ForeignKey(
                help_text="Event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="events.event",
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="eventfeedback",
            name="user",
            field=models.ForeignKey(
                help_text="User",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_feedback",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="eventinteractions",
            name="event",
            field=models.ForeignKey(
                help_text="Event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="events.event",
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="eventinteractions",
            name="user",
            field=models.ForeignKey(
                help_text="User",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_interactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="eventnotificationconfig",
            name="event",
            field=models.ForeignKey(
                help_text="Event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_config",
                to="events.event",
                verbose_name="event",
            ),
        ),
    ]
