# Generated by Django 5.1.7 on 2025-03-22 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventnotificationconfig_reminder_mail_sent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image",
                        upload_to="event_images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Uploaded At",
                        verbose_name="uploaded at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated At", verbose_name="updated at"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="events.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Image",
                "verbose_name_plural": "Event Images",
            },
        ),
    ]
